import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../../styles/Home.module.css'

const Page: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Engineering Study Club</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Collaborative GraphQL and Advanced Usecases
        </h1>
      </main>

      <footer className={styles.footer}>
      <a href="/">🏡</a> written by tehnix / codetalk.io <a href="/slides/1">👉</a>
      </footer>
    </div>
  )
}

export default Page;
