subgraphs:
  users:
    routing_url: http://localhost:4001
    schema:
      subgraph_url: http://localhost:4002
  reviews:
    routing_url: http://localhost:4002
    schema:
      subgraph_url: http://localhost:4002
  products:
    routing_url: http://localhost:4003
    schema:
      subgraph_url: http://localhost:4003
