import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Engineering Study Club</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Collaborative GraphQL and Advanced Usecases
        </h1>

        <div className={styles.grid}>
          <a
            href="http://localhost:4000/"
            target="_blank"
            className={styles.card}
            rel="noreferrer"
          >
            <h2>Apollo Studio &rarr;</h2>
            <p>Explore the GraphQL API with Apollo Studio.</p>
          </a>

          <a href="/slides" className={styles.card}>
            <h2>Slides &rarr;</h2>
            <p>Jump to the slides going through GraphQL.</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>written by tehnix / codetalk.io</footer>
    </div>
  );
};

export default Home;
